- hosts: all

  vars:
    version: "v0.0.7"
    arch: "arm64"
    binary_url: "https://github.com/Carbonique/voetbalpoules/releases/download/{{ version }}/voetbalpoules-{{ version }}-linux-{{ arch }}.tar.gz"
    directory: "/home/{{ user }}/voetbalpoules"

  tasks:
    - name: Create directory if not exists
      ansible.builtin.file:
        path: '{{ directory }}'
        state: directory
        mode: '0755'

    - name: Download and unarchive binary
      ansible.builtin.unarchive:
        src: "{{ binary_url }}"
        dest: "{{ directory }}"
        remote_src: yes

    - name: Check if .env file exists on Ansible controller
      delegate_to: localhost
      stat:
        path: "{{ playbook_dir }}/.env"
      register: env_file

    - name: Copy .env file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/.env"
        dest: "{{ directory }}"
      when: env_file.stat.exists

    - name: Setup cron
      ansible.builtin.cron:
        name: "{{ item.name }}"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour }}"
        job: "{{ item.job }}"
      loop:
        - { name: 'Wedstrijd voorspellingen vooraf', minute: 30, hour: '10,13,16,19', job: '{{ directory }}/voetbalpoules voorspelling'}
        - { name: 'Wedstrijd voorspellingen definitief', minute: 0, hour: '11,14,17,20', job: 'sleep 10 && {{ directory }}/voetbalpoules voorspelling --time -5'}
        - { name: 'Wedstrijd uitslag', minute: 5, hour: '13,16,19,22', job: '{{ directory }}/voetbalpoules uitslag --time -150'}
        - { name: 'Wedstrijd stand', minute: 10, hour: '13,16,19,22', job: '{{ directory }}/voetbalpoules stand --time -150'}